name: "AWS SSM Get-Invocation Output"
author: "Fabio Antonio González Sosa <fabio.gonzalez@itti.digital>"

description: "Obtiene la salida de un comando ejecutado remotamente vía AWS SSM."

inputs:
  aws-access-key-id:
    required: true
    description: "AWS access key id"
  aws-secret-access-key:
    required: true
    description: "AWS secret access key"
  aws-region:
    required: true
    description: "Where EC2 instance is"
  instance-id:
    required: true
    description: "AWS EC2 Instance id"
  command-id:
    required: true
    description: "AWS SSM Command id"

runs:
  using: "node16"
  main: "index.js"